# config.yaml
models:
  
  RandomForest: 
    type: "RandomForestClassifier"
    params:
      n_estimators: [500, 1000, 1500]                     
      class_weight: ["balanced", "balanced_subsample"]    
      max_depth: [10, 15]                                 
      min_samples_leaf: [10]                              
      max_features: ["sqrt", "log2"]                      
      bootstrap: [true]
      n_jobs: [-1]                                   
      

  xgboost: 
    type: "XGBClassifier"
    params:
      scale_pos_weight: [70.4]        
      max_depth: [3, 6]                     
      min_child_weight: [10]                
      gamma: [1.5]                          
      lambda: [2.0]                         
      alpha: [0.5]                          
      subsample: [0.8]                      
      colsample_bytree: [0.8]               
      learning_rate: [0.01]                 
      n_estimators: [500, 1000, 1500]       
      tree_method: ["hist" ]                
      

evaluation:    
  metrics: ["aucpr", "f1", "precision", "recall"]
  stratify: y
