# config.yaml
models:
  
  random_forest:
    type: "RandomForestClassifier"
    params:
      n_estimators: 1000                    # More trees help identify rare minority patterns
      class_weight: "balanced_subsample"    # Penalizes fraud misclassifications based on tree bootstrap samples
      max_depth: 15                         # Prevents memorizing noise in majority data
      min_samples_leaf: 10                  # Ensures leaves are statistically significant, reducing false positives
      max_features: "sqrt"                  # Standard for diverse trees in ensemble
      bootstrap: true
      n_jobs: -1                            # Use all available CPU cores for speed
      random_state: 42


  
  logistic_regression:
    type: "LogisticRegression"
    params:
      class_weight: "balanced"      # Automatically scales weights to 1:70 ratio
      penalty: "l1"                 # Use L1 to eliminate noise/useless features
      C: 0.1                        # Stronger regularization (default is 1.0)
      solver: "saga"                # Handles L1 and scales well to large data
      max_iter: 1000                # Ensures the model converges on imbalanced data
      random_state: 42



  xgboost: 
    type: "XGBClassifier"
    params:
      scale_pos_weight: 70.4        
      max_depth: 6                  # Shallow trees are more robust for rare events
      min_child_weight: 10          # Higher values prevent splitting on single fraud cases
      gamma: 1.5                    # Minimum loss reduction to split; adds conservatism
      lambda: 2.0                   # L2 regularization to keep leaf weights stable
      alpha: 0.5                    # L1 regularization for feature sparsity
      subsample: 0.8                # Rows sampled per tree to increase robustness
      colsample_bytree: 0.8         # Features sampled per tree
      learning_rate: 0.05           # Low rate + more estimators is better for fraud
      n_estimators: 1000
      early_stopping_rounds: 50     # Stop if AUCPR stops improving
      tree_method: "hist",          # Faster training for large datasets
      eval_metric: 'aucpr'          # Use AUC-PR for evaluation
      random_state: 42




evaluation:
  # Crucial: Use Area Under Precision-Recall Curve for 1.4% imbalance
  eval_metric: "aucpr"            
  validation_size: 0.2
  stratify: true
